name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reporting the issue, we are checking the issue internally and will feedback to you soon '
        pr-message: 'Hi, we are setting up the contribution license model so there will be several days delay on merging your patch. Appreciate for you understanding. '
