name: Manual workflow

on:
  [pull_request, workflow_dispatch]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issues = await github.paginate(github.issues.listForRepo, {
              owner: "suchun230",
              repo: 'test-cla',
              state: 'open'
            })

            for (const issue of issues) {
              await github.issues.createComment({
                issue_number: issue.number,
                owner: "suchun230",
                repo: "test-cla",
                body: 'Hi, we are setting up contribution license model'
              })
            }
