name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'issue number'
        # Default value if no value is explicitly provided
        default: 1
        # Input has to be provided for the workflow to run
        required: true

jobs:
  comment issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const creator = context.payload.sender.login
            const opts = github.issues.listForRepo.endpoint.merge({
              state: 'open'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Welcome, new contributor!'
              }
            })
